# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "NTAnalyticsSample" do

pod 'FlurrySDK'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'

# we map these directly to the podspecs in the project for testing

pod 'NTAnalytics', :path => '~/Projects/NagelTech/NTAnalytics/NTAnalytics.podspec'

end

